version: "3"
tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - protoc -I protos protos/proto/sso/*.proto --go_out=./protos/gen/go/ --go_opt=paths=source_relative --go-grpc_out=./protos/gen/go/ --go-grpc_opt=paths=source_relative

  build:
    desc: "Compile the project"
    cmds:
    - go build -o app main.go

  clean:
    desc: "Clean build artifacts"
    cmds:
      - rm -f app

  install:
    desc: "Install dependencies"
    cmds:
      - go mod tidy

  run:
    desc: "Run the application"
    cmds:
      -  go run sso/cmd/sso/main.go --config=./sso/cmd/config/local.yaml

